#==========================================================================
# Description: Upload test
#==========================================================================

name: Upload test

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          mkdir -p /tmp/builder/
          cp -a /proc/cpuinfo /tmp/builder/
          cp -a /proc/meminfo /tmp/builder/
          uname -a > /tmp/builder/kernel.txt
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload files to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        with:
          tag: upload_test
          artifacts: /tmp/builder/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### Action upload test
            This is just test
            - upload cpuinfo
              * /proc/cpuinfo
            - upload meminfo
              * /proc/meminfo
            - upload release
              * ```uname -a > /tmp/builder/kernel.txt```